name: Deploy on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Validate JSON files in public/data folder
        run: |
          npm install -g jsonlint
          JSON_FILES=$(find public/data -name '*.json')
          if [ -n "$JSON_FILES" ]; then
            jsonlint $JSON_FILES -q
          else
            echo "No JSON files found in public/data folder."
          fi

      - name: Set up Git config
        run: |
          git config --global user.email "inclusiveeducation@tudelft.nl"
          git config --global user.name "Inclusive Education"

      - name: Run deploy
        if: success()
        run: npm run deploy
