name: Deploy on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Validate JSON files in public/data folder
        run: |
          npm install -g jsonlint
          if [ "$(find public/data -name '*.json')" ]; then
            jsonlint "./public/data/**/*.json" -q
          else
            echo "No JSON files found in the public/data folder."
          fi

      - name: Run deploy
        if: success()
        run: npm run deploy
