name: Deploy on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Install dependencies
        run: npm install

      - name: Validate JSON files
        run: |
          npm install -g jsonlint
          jsonlint "**/*.json" -q

      - name: Run deploy
        if: success()
        run: npm run deploy
