name: CI CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Validate JSON files in public/data folder
        run: |
          npm install -g jsonlint
          JSON_FILES=$(find public/data -name '*.json')
          if [ -n "$JSON_FILES" ]; then
            jsonlint $JSON_FILES -q
          else
            echo "No JSON files found in public/data folder."
          fi

      - name: Run deploy
        if: success()
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: 'Inclusive Education'
          user_email: 'inclusiveeducation@tudelft.nl'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
